cins, cdel = 3.0, 3.0
horiz_adj = 1.5
similar_letter = 2.0
vert_adj = 2.5
diag_adj = 3.5
no_adj = 5.5

# Generated by hand...
# These are all of the proximity values of a-z
KeyboardGraph = {'a': {'q': vert_adj,
                       'w': diag_adj,
                       's': horiz_adj,
                       'z': vert_adj,
                       'x': diag_adj,
                       'e': similar_letter,
                       'o': similar_letter,
                       'u': similar_letter,
                       # ------
                       'b': no_adj,
                       'c': no_adj,
                       'd': no_adj,
                       'f': no_adj,
                       'g': no_adj,
                       'h': no_adj,
                       'i': no_adj,
                       'j': no_adj,
                       'k': no_adj,
                       'l': no_adj,
                       'm': no_adj,
                       'n': no_adj,
                       'p': no_adj,
                       'r': no_adj,
                       't': no_adj,
                       'v': no_adj,
                       'y': no_adj},
                 'b': {'f': diag_adj,
                       'g': vert_adj,
                       'h': diag_adj,
                       'v': horiz_adj,
                       'n': horiz_adj,
                       # ------
                       'c': no_adj,
                       'd': no_adj,
                       'e': no_adj,
                       'i': no_adj,
                       'j': no_adj,
                       'k': no_adj,
                       'l': no_adj,
                       'm': no_adj,
                       'o': no_adj,
                       'p': no_adj,
                       'q': no_adj,
                       'r': no_adj,
                       's': no_adj,
                       't': no_adj,
                       'u': no_adj,
                       'w': no_adj,
                       'x': no_adj,
                       'y': no_adj,
                       'z': no_adj},
                 'c': {'d': vert_adj,
                       'f': diag_adj,
                       'x': horiz_adj,
                       'v': horiz_adj,
                       's': similar_letter,
                       'k': similar_letter,
                       # ------
                       'e': no_adj,
                       'g': no_adj,
                       'h': no_adj,
                       'i': no_adj,
                       'j': no_adj,
                       'l': no_adj,
                       'm': no_adj,
                       'n': no_adj,
                       'o': no_adj,
                       'p': no_adj,
                       'q': no_adj,
                       'r': no_adj,
                       't': no_adj,
                       'u': no_adj,
                       'w': no_adj,
                       'y': no_adj,
                       'z': no_adj},
                 'd': {'w': diag_adj,
                       'e': vert_adj,
                       'r': diag_adj,
                       's': horiz_adj,
                       'f': horiz_adj,
                       'x': diag_adj,
                       'v': diag_adj,
                       't': similar_letter,
                       # ------
                       'g': no_adj,
                       'h': no_adj,
                       'i': no_adj,
                       'j': no_adj,
                       'k': no_adj,
                       'l': no_adj,
                       'm': no_adj,
                       'n': no_adj,
                       'o': no_adj,
                       'p': no_adj,
                       'q': no_adj,
                       'u': no_adj,
                       'y': no_adj,
                       'z': no_adj},
                 'e': {'w': horiz_adj,
                       'r': horiz_adj,
                       's': diag_adj,
                       'f': diag_adj,
                       'i': similar_letter,
                       'u': similar_letter,
                       'y': similar_letter,
                       # ------
                       'g': no_adj,
                       'h': no_adj,
                       'j': no_adj,
                       'k': no_adj,
                       'l': no_adj,
                       'm': no_adj,
                       'n': no_adj,
                       'o': no_adj,
                       'p': no_adj,
                       'q': no_adj,
                       't': no_adj,
                       'v': no_adj,
                       'x': no_adj,
                       'z': no_adj},
                 'f': {'r': vert_adj,
                       't': diag_adj,
                       'g': horiz_adj,
                       'v': vert_adj,
                       'p': similar_letter,  # for 'ph'
                       # ------
                       'h': no_adj,
                       'i': no_adj,
                       'j': no_adj,
                       'k': no_adj,
                       'l': no_adj,
                       'm': no_adj,
                       'n': no_adj,
                       'o': no_adj,
                       'q': no_adj,
                       's': no_adj,
                       'u': no_adj,
                       'w': no_adj,
                       'x': no_adj,
                       'y': no_adj,
                       'z': no_adj},
                 'g': {'r': diag_adj,
                       't': vert_adj,
                       'y': diag_adj,
                       'h': horiz_adj,
                       'v': diag_adj,
                       'n': diag_adj,
                       'j': similar_letter,
                       # ------
                       'i': no_adj,
                       'k': no_adj,
                       'l': no_adj,
                       'm': no_adj,
                       'o': no_adj,
                       'p': no_adj,
                       'q': no_adj,
                       's': no_adj,
                       'u': no_adj,
                       'w': no_adj,
                       'x': no_adj,
                       'z': no_adj},
                 'h': {'t': diag_adj,
                       'y': vert_adj,
                       'u': diag_adj,
                       'j': horiz_adj,
                       'n': vert_adj,
                       'm': diag_adj,
                       # ------
                       'i': no_adj,
                       'k': no_adj,
                       'l': no_adj,
                       'o': no_adj,
                       'p': no_adj,
                       'q': no_adj,
                       'r': no_adj,
                       's': no_adj,
                       'v': no_adj,
                       'w': no_adj,
                       'x': no_adj,
                       'z': no_adj},
                 'i': {'u': horiz_adj,
                       'o': horiz_adj,
                       'j': diag_adj,
                       'k': vert_adj,
                       'l': diag_adj,
                       'y': similar_letter,
                       # ------
                       'm': no_adj,
                       'n': no_adj,
                       'p': no_adj,
                       'q': no_adj,
                       'r': no_adj,
                       's': no_adj,
                       't': no_adj,
                       'v': no_adj,
                       'w': no_adj,
                       'x': no_adj,
                       'z': no_adj},
                 'j': {'y': diag_adj,
                       'u': vert_adj,
                       'k': horiz_adj,
                       'n': diag_adj,
                       'm': vert_adj,
                       # ------
                       'l': no_adj,
                       'o': no_adj,
                       'p': no_adj,
                       'q': no_adj,
                       'r': no_adj,
                       's': no_adj,
                       't': no_adj,
                       'v': no_adj,
                       'w': no_adj,
                       'x': no_adj,
                       'z': no_adj},
                 'k': {'u': diag_adj,
                       'o': diag_adj,
                       'l': horiz_adj,
                       'm': diag_adj,
                       # ------
                       'n': no_adj,
                       'p': no_adj,
                       'q': no_adj,
                       'r': no_adj,
                       's': no_adj,
                       't': no_adj,
                       'v': no_adj,
                       'w': no_adj,
                       'x': no_adj,
                       'y': no_adj,
                       'z': no_adj},
                 'l': {'o': vert_adj,
                       'p': diag_adj,
                       # ------
                       'm': no_adj,
                       'n': no_adj,
                       'q': no_adj,
                       'r': no_adj,
                       's': no_adj,
                       't': no_adj,
                       'u': no_adj,
                       'v': no_adj,
                       'w': no_adj,
                       'x': no_adj,
                       'y': no_adj,
                       'z': no_adj},
                 'm': {'n': horiz_adj,
                       # ------
                       'o': no_adj,
                       'p': no_adj,
                       'q': no_adj,
                       'r': no_adj,
                       's': no_adj,
                       't': no_adj,
                       'u': no_adj,
                       'v': no_adj,
                       'w': no_adj,
                       'x': no_adj,
                       'y': no_adj,
                       'z': no_adj},
                 # ------
                 'n': {'o': no_adj,
                       'p': no_adj,
                       'q': no_adj,
                       'r': no_adj,
                       's': no_adj,
                       't': no_adj,
                       'u': no_adj,
                       'v': no_adj,
                       'w': no_adj,
                       'x': no_adj,
                       'y': no_adj,
                       'z': no_adj},
                 'o': {'u': similar_letter,
                       # ------
                       'p': no_adj,
                       'q': no_adj,
                       'r': no_adj,
                       's': no_adj,
                       't': no_adj,
                       'v': no_adj,
                       'w': no_adj,
                       'x': no_adj,
                       'y': no_adj,
                       'z': no_adj},
                 # ------
                 'p': {'q': no_adj,
                       'r': no_adj,
                       's': no_adj,
                       't': no_adj,
                       'u': no_adj,
                       'v': no_adj,
                       'w': no_adj,
                       'x': no_adj,
                       'y': no_adj,
                       'z': no_adj},
                 'q': {'w': horiz_adj,
                       's': diag_adj,
                       # ------
                       'r': no_adj,
                       't': no_adj,
                       'u': no_adj,
                       'v': no_adj,
                       'x': no_adj,
                       'y': no_adj,
                       'z': no_adj},
                 'r': {'t': horiz_adj,
                       # ------
                       's': no_adj,
                       'u': no_adj,
                       'v': no_adj,
                       'w': no_adj,
                       'x': no_adj,
                       'y': no_adj,
                       'z': no_adj},
                 's': {'w': vert_adj,
                       'z': diag_adj,
                       'x': vert_adj,
                       # ------
                       't': no_adj,
                       'u': no_adj,
                       'v': no_adj,
                       'y': no_adj},
                 't': {'y': horiz_adj,
                       # ------
                       'u': no_adj,
                       'v': no_adj,
                       'w': no_adj,
                       'x': no_adj,
                       'z': no_adj},
                 'u': {'y': horiz_adj,
                       # ------
                       'v': no_adj,
                       'w': no_adj,
                       'x': no_adj,
                       'z': no_adj},
                 # ------
                 'v': {'w': no_adj,
                       'x': no_adj,
                       'y': no_adj,
                       'z': no_adj},
                 # ------
                 'w': {'x': no_adj,
                       'y': no_adj,
                       'z': no_adj},
                 'x': {'z': horiz_adj,
                       # ------
                       'y': no_adj},
                 # ------
                 'y': {'z': no_adj}}
alphabet = 'abcdefghijklmnopqrstuvwxyz'


# This will calculate the substitution cost of letters.
# If the letter is the same, the cost is 0. The max cost is no_adj
def csub(a, b):
    global alphabet
    a, b = a.lower(), b.lower()
    if a not in alphabet or b not in alphabet:
        return no_adj
    if a == b:
        return 0.0
    elif a < b:
        return KeyboardGraph[a][b]
    else:
        return KeyboardGraph[b][a]


# This returns the distance between two strings.
# This is modified from the old assigment in that it
# weights substitutions by proximity on a (QWERTY) keyboard.
def str_dist(str1, str2):
    # The cost of substitutions, insertions, and deletions respectively
    l1, l2 = len(str1), len(str2)
    arr = [[0] * (l1 + 1) for x in range(l2 + 1)]
    for i in range(1, l2 + 1):
        arr[i][0] = i * cins
    for j in range(1, l1 + 1):
        arr[0][j] = j * cdel
    for i in range(1, l2 + 1):
        for j in range(1, l1 + 1):
            c = csub(str1[j - 1], str2[i - 1])
            arr[i][j] = min(arr[i][j - 1] + cdel,
                            arr[i - 1][j] + cins,
                            arr[i - 1][j - 1] + c)
    return arr[l2][l1]


def main():
    global alphabet
    print ',' + ','.join(alphabet)
    for a in alphabet:
        to_p = a
        for b in alphabet:
            to_p += ',' + str(csub(a, b))
        print to_p

if __name__ == '__main__':
    main()
